name: 🔨 Build Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:  
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    services:
      gotify:
        image: ghcr.io/gotify/server
        ports:
          - 80:80
        options: >-
          -v /var/gotify/data:/app/data
          --name gotify

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test .
        working-directory: cmd/notify/

      - name: Build
        run: go build .
        working-directory: cmd/notify/
  
      # - name: Integration Tests
      #   run: |
      #     chmod +x gotify.sh
      #     chmod +x action-run.sh
      #     bash action-run.sh
      #   working-directory: cmd/integration-test/